import { makeQuestions, type QuestionSeed } from './helpers';

const algorithmSeeds: QuestionSeed[] = [
  {
    id: 'b-algorithm-043', topic: 'ループ境界',
    stem: '1から7までの整数を2ずつ増やして加算する擬似言語を実行したとき、返却値はどれか。',
    code: '手続 stepSum\ns ← 0\nfor i ← 1 to 7 step 2\n  s ← s + i\nendfor\nreturn s',
    answer: '16', why: 'iは1、3、5、7と変化するため、1＋3＋5＋7を計算して16になります。',
    wrong: [['12', '最後の7を加えず、1＋3＋5までで止めた値です。'], ['18', '2ずつ増える値を全て足す過程で7を二重に数えています。'], ['28', '1から7までを1ずつ増やして加えた値と取り違えています。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-algorithm-044', topic: '早期終了',
    stem: '配列を先頭から調べ、値8を初めて見つけた位置を直ちに返す処理の結果はどれか。',
    code: '手続 firstEight\na ← [3, 8, 5, 8]\nfor i ← 1 to 4\n  if a[i] = 8 then return i endif\nendfor\nreturn 0',
    answer: '2', why: '先頭から調べると2番目の8でreturnが実行され、後の8は調べません。',
    wrong: [['4', '後に現れる8まで処理を続ける問題ではありません。'], ['8', '返す値は一致した要素値ではなく位置です。'], ['0', '0は最後まで見つからなかった場合の返却値です。']],
    position: 2, difficulty: 2,
  },
  {
    id: 'b-algorithm-045', topic: 'continue',
    stem: '配列から奇数だけを合計する処理で、continueが実行された後の返却値を求める。',
    code: '手続 oddSum\na ← [2, 5, 8, 1]\ns ← 0\nfor each v in a\n  if v mod 2 = 0 then continue endif\n  s ← s + v\nendfor\nreturn s',
    answer: '6', why: '偶数2と8ではcontinueして加算せず、奇数5と1だけを足すので6です。',
    wrong: [['16', '偶数も含めた全要素の合計です。'], ['5', '最後の奇数1を加え忘れています。'], ['8', '加算する奇数の合計ではなく、配列中の偶数の一つです。']],
    position: 0, difficulty: 2,
  },
  {
    id: 'b-algorithm-046', topic: 'ループ停止条件',
    stem: '値を3ずつ減らし、0以下になった時点で停止する処理の更新回数を求める。',
    code: '手続 decrease\nn ← 10\nc ← 0\nwhile n > 0\n  n ← n - 3\n  c ← c + 1\nendwhile\nreturn c',
    answer: '4回', why: 'nは10、7、4、1、-2と変化するため、更新は4回で条件が偽になります。',
    wrong: [['3回', '1から-2への最後の更新を数えていません。'], ['10回', '減少量3を無視して初期値を回数にしています。'], ['5回', '0になった後も一度実行すると考えています。']],
    position: 3, difficulty: 2,
  },
  {
    id: 'b-algorithm-047', topic: '二分探索の範囲更新',
    stem: '昇順配列で中央値21を調べた結果、目的値35の探索範囲を次にどう更新するか。',
    code: '手続 narrow\na ← [3, 8, 14, 21, 29, 35, 42]\nlow ← 1, high ← 7\nmid ← (low + high) div 2\nif a[mid] < 35 then low ← mid + 1 endif\nreturn low, high',
    answer: 'low=5、high=7', why: '21は35より小さいため、中央位置4より左を捨ててlowを5へ進めます。',
    wrong: [['low=1、high=3', '目的値が中央値より大きいときは右側を残します。'], ['low=4、high=7', '中央位置自身を次の探索範囲へ残していません。'], ['low=5、high=6', 'この一回の更新では末尾42を除外する条件はありません。']],
    position: 1, difficulty: 3,
  },
  {
    id: 'b-algorithm-048', topic: '選択ソートの途中状態',
    stem: '選択ソートで先頭要素を確定した直後、未整列部分から最小値を選んで交換した配列はどれか。',
    code: '手続 selectSecond\na ← [7, 9, 6, 3]\n先頭の交換後 a は [3, 9, 6, 7]\nmin ← 2\nfor j ← 3 to 4\n  if a[j] < a[min] then min ← j endif\nendfor\nswap(a[2], a[min])\nreturn a',
    answer: '[3, 6, 9, 7]', why: '未整列部分[9,6,7]の最小値6を2番目の9と交換するため、この状態になります。',
    wrong: [['[3, 7, 6, 9]', '未整列部分の最小値ではなく末尾値を移動しています。'], ['[6, 3, 9, 7]', '確定済みの先頭3まで交換対象にしています。'], ['[3, 6, 7, 9]', 'この段階では残りの要素まで整列し終えていません。']],
    position: 0, difficulty: 3,
  },
  {
    id: 'b-algorithm-049', topic: '挿入ソートの途中状態',
    stem: '整列済み部分へ次の要素を挿入する処理を一回行った後の配列を選ぶ。',
    code: '手続 insertStep\na ← [2, 5, 9, 11, 7]\nkey ← a[5]\nj ← 4\nwhile j >= 1 and a[j] > key\n  a[j+1] ← a[j]\n  j ← j - 1\nendwhile\na[j+1] ← key\nreturn a',
    answer: '[2, 5, 7, 9, 11]', why: '11と9を一つ右へ移し、5と9の間へkeyの7を入れるので昇順になります。',
    wrong: [['[2, 7, 5, 9, 11]', '7は5より大きく、5の前へは挿入しません。'], ['[2, 5, 9, 7, 11]', '9を右へ移す操作を反映していません。'], ['[7, 2, 5, 9, 11]', '比較対象の先頭を越えて挿入する処理ではありません。']],
    position: 2, difficulty: 2,
  },
  {
    id: 'b-algorithm-050', topic: 'クイックソートの分割',
    stem: 'ピボットより小さい値を左へ集める分割処理を実行した直後の配列を求める。',
    code: '手続 partition\na ← [9, 4, 7, 2, 6]\npivot ← a[5]\ni ← 1\nfor j ← 1 to 4\n  if a[j] < pivot then swap(a[i], a[j]); i ← i + 1 endif\nendfor\nswap(a[i], a[5])\nreturn a',
    answer: '[4, 2, 6, 9, 7]', why: 'pivotの6より小さい4と2を左へ集め、その直後の位置へ6を置きます。',
    wrong: [['[2, 4, 6, 7, 9]', '分割一回で左右の部分配列まで整列した結果です。'], ['[9, 4, 7, 2, 6]', '4と2を見つけた交換を反映していません。'], ['[4, 2, 7, 9, 6]', '最後にpivotを境界位置へ交換する処理が抜けています。']],
    position: 3, difficulty: 3,
  },
  {
    id: 'b-algorithm-051', topic: '安定ソート',
    stem: '得点が同じ受験者の元の順序を保ったまま得点順に並べる必要がある。適切な性質はどれか。',
    code: '手続 stableSort\n得点が同じ要素の比較では、元の順序を交換しない\n得点の昇順に整列する\nreturn list',
    answer: '安定性', why: 'キーが同じ要素の相対順序を保つ性質を安定性といい、同点者の順序を維持できます。',
    wrong: [['完全二分性', '探索木の分岐条件を表す語で、同値要素の順序とは関係しません。'], ['ランダム性', '入力順を意図的に保つ性質ではありません。'], ['排他性', '同時実行時の資源制御を表す概念です。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-algorithm-052', topic: '二ポインタ法',
    stem: '昇順配列から合計が10になる二要素を両端から探す処理で、最初に見つかる組を求める。',
    code: '手続 pair\na ← [1, 3, 4, 6, 8]\nleft ← 1, right ← 5\nwhile left < right\n  s ← a[left] + a[right]\n  if s = 10 then return a[left], a[right] endif\n  if s < 10 then left ← left + 1 else right ← right - 1 endif\nendwhile',
    answer: '4と6', why: '最初は1＋8が9なのでleftを進め、3＋8が11でrightを戻し、最後に4＋6が10になります。',
    wrong: [['3と6', '合計は9であり、条件10を満たしません。'], ['3と8', '合計は11であり、条件一致として返せません。'], ['4と8', '合計は12であり、条件一致として返せません。']],
    position: 0, difficulty: 3,
  },
  {
    id: 'b-algorithm-053', topic: '累積和の区間取得',
    stem: '累積和配列を使って、元配列の2番目から4番目までの合計を求める式と値はどれか。',
    code: '手続 rangeSum\na ← [4, 6, 3, 8]\np[1] ← 4\np[2] ← 10\np[3] ← 13\np[4] ← 21\nreturn p[4] - p[1]',
    answer: '17', why: 'p[4]から1番目までの累積13ではなく、p[4]−p[1]=21−4で2〜4番目の17を求めます。',
    wrong: [['21', '1番目から4番目までの全体の累積値です。'], ['13', '3番目までの累積値で、4番目の値を含んでいません。'], ['10', '1番目から2番目までの累積値です。']],
    position: 2, difficulty: 2,
  },
  {
    id: 'b-algorithm-054', topic: 'スライディングウィンドウ',
    stem: '連続する3日間の売上合計の最大値を、窓を一日ずつ右へ移動して求める。',
    code: '手続 maxWindow\na ← [4, 7, 2, 9, 5]\nwindow ← a[1] + a[2] + a[3]\nbest ← window\nfor right ← 4 to 5\n  window ← window - a[right-3] + a[right]\n  if window > best then best ← window endif\nendfor\nreturn best',
    answer: '18', why: '窓の合計は13、18、16と変わるため、最大値bestは18になります。',
    wrong: [['20', '全要素の合計に近い値で、連続3日という条件を外しています。'], ['16', '最後の窓の合計を最大値と取り違えています。'], ['13', '最初の窓から更新されないと考えています。']],
    position: 3, difficulty: 3,
  },
  {
    id: 'b-algorithm-055', topic: '括弧の対応',
    stem: '開き括弧と閉じ括弧が正しく対応しているかを調べる処理で、文字列の判定結果を求める。',
    code: '手続 brackets\ns ← "(()())"\nstack ← 空\nfor each ch in s\n  if ch = "(" then push(ch) else if stack is empty then return false else pop() endif endif\nendfor\nreturn stack is empty',
    answer: 'true', why: '閉じ括弧のたびに対応する開き括弧をpopでき、最後にスタックも空になるためtrueです。',
    wrong: [['false', '開き括弧と閉じ括弧の数だけでなく順序も正しく対応しています。'], ['6', '返却値は文字数ではなく対応判定の真偽値です。'], ['空でない', '最後の閉じ括弧まで処理すると全ての開き括弧が取り出されます。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-algorithm-056', topic: '循環キュー',
    stem: '容量4の循環キューで末尾位置を一周させながら追加したとき、次の格納位置を求める。',
    code: '手続 circular\nsize ← 4\nrear ← 3\nqueue[rear]へXを格納\nrear ← (rear + 1) mod size\nreturn rear',
    answer: '0', why: 'rearが3のとき次の位置は(3＋1) mod 4で0となり、配列の先頭へ戻ります。',
    wrong: [['4', '剰余を取るため、添字4は容量4の配列では使いません。'], ['3', '格納前のrearをそのまま返していません。'], ['1', '一周後の0からさらに進めた位置と混同しています。']],
    position: 0, difficulty: 2,
  },
  {
    id: 'b-algorithm-057', topic: '連結リスト削除',
    stem: '単方向リストA→B→CからBを削除するポインタ操作後の並びを選ぶ。',
    code: '手続 deleteB\nhead → A → B → C → null\nA.next ← B.next\nreturn list',
    answer: 'A → C', why: 'AのnextをBの次であるCへつなぎ替えるため、Bを飛ばしたA→Cになります。',
    wrong: [['B → C', 'headをAからBへ変更する処理ではありません。'], ['A → B', 'A.nextのつなぎ替えを反映していません。'], ['A → C → B', '削除対象Bを末尾へ移動する処理ではありません。']],
    position: 2, difficulty: 2,
  },
  {
    id: 'b-algorithm-058', topic: '連結リスト挿入',
    stem: '単方向リストA→CのAとCの間へBを挿入する正しいポインタ操作を選ぶ。',
    code: '手続 insertB\nhead → A → C → null\nB.next ← A.next\nA.next ← B\nreturn list',
    answer: 'A → B → C', why: '先にBのnextをCへ向け、その後AのnextをBへ変えるので、AとCの間にBが入ります。',
    wrong: [['B → A → C', 'headをBへ変更する先頭挿入の操作ではありません。'], ['A → C → B', 'Cの後ろへ追加する操作と取り違えています。'], ['A → B', 'B.nextを旧A.nextへ設定しているためCも残ります。']],
    position: 3, difficulty: 2,
  },
  {
    id: 'b-algorithm-059', topic: '木の高さ',
    stem: '二分木の高さを、空の木を0として再帰的に求める関数へ木を渡した結果はどれか。',
    code: '手続 height(node)\nif node = null then return 0\nleft ← height(node.left)\nright ← height(node.right)\nreturn max(left, right) + 1',
    answer: '最長の根から葉までの節点数', why: '左右部分木の高さの大きい方へ根の1を加えるため、最長経路上の節点数になります。',
    wrong: [['葉の個数', '左右の葉を数える処理ではなく、深さの最大値を求めています。'], ['全節点数', '短い枝の節点まで加算する処理ではありません。'], ['最短経路の節点数', 'maxを使うため最長側の高さが採用されます。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-algorithm-060', topic: 'ヒープ',
    stem: '最小ヒープの根を取り出した後、最後の要素を根へ移して下方向へ調整する目的は何か。',
    code: '手続 removeMin\nroot ← heap[1]\nheap[1] ← heap[last]\nlast ← last - 1\nwhile child is smaller than heap[parent]\n  swap(parent, child)\nendwhile\nreturn root',
    answer: '最小要素を根に保つ', why: '根へ移した要素を小さい子と交換し続け、再び親が子以下となるヒープ条件を回復します。',
    wrong: [['要素を降順へ整列する', 'ヒープ調整は全配列の完全整列を目的にしません。'], ['根を最大要素にする', '最小ヒープでは根が最小要素です。'], ['木を完全二分木でなくする', '最後の要素を使うことで形状を保ちながら値を調整します。']],
    position: 0, difficulty: 3,
  },
  {
    id: 'b-algorithm-061', topic: 'グラフの次数',
    stem: '無向グラフの隣接行列で、頂点2から出る辺の本数を数える処理の結果を求める。',
    code: '手続 degree\nm ← [[0,1,1],[1,0,1],[1,1,0]]\nc ← 0\nfor j ← 1 to 3\n  if m[2][j] = 1 then c ← c + 1 endif\nendfor\nreturn c',
    answer: '2', why: '頂点2の行には頂点1と3への1が二つあるため、次数は2です。',
    wrong: [['1', '自分自身への対角要素0を除いて一辺だけと数えています。'], ['3', '行の要素数をそのまま辺数にしています。'], ['0', '対角要素だけを調べた値ではありません。']],
    position: 2, difficulty: 2,
  },
  {
    id: 'b-algorithm-062', topic: '深さ優先探索の訪問順',
    stem: '隣接頂点を番号の小さい順にスタックへ積む深さ優先探索の訪問順を求める。',
    code: '手続 dfs\n1の隣接は2,3、2の隣接は4\nstack.push(1)\n未訪問頂点を取り出し、隣接頂点を小さい順にpushする\nreturn visit order',
    answer: '1, 3, 2, 4', why: '2と3を積むと後から積んだ3を先に取り出すため、3を処理してから2、最後に4を訪問します。',
    wrong: [['1, 2, 4, 3', 'キューのように先に積んだ2を先に取り出しています。'], ['1, 2, 3, 4', 'スタックのLIFO順を反映していません。'], ['4, 2, 3, 1', '始点1から始める条件を無視しています。']],
    position: 3, difficulty: 3,
  },
  {
    id: 'b-algorithm-063', topic: '幅優先探索の距離',
    stem: '無向グラフを幅優先探索し、始点から頂点5までの最短辺数を求める。',
    code: '手続 bfs\n1→2,3\n2→4\n3→5\nqueueへ1を入れ、取り出した頂点の距離+1を隣接頂点へ設定する\nreturn distance[5]',
    answer: '2', why: '1から3へ1辺、3から5へ1辺なので、頂点5の距離は2です。',
    wrong: [['1', '頂点5は始点1の直接の隣接頂点ではありません。'], ['3', '訪問した頂点数を距離と取り違えています。'], ['4', '頂点2から4へ進む経路の長さを使っています。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-algorithm-064', topic: 'トポロジカルソート',
    stem: 'ある組織の作業で、依存関係A→C、B→C、C→Dを満たす作業順として適切なものはどれか。',
    code: '手続 topo\n入次数0の頂点を選び、削除して次の候補を追加する\n依存辺 A→C, B→C, C→D\nreturn order',
    answer: 'A, B, C, D', why: 'Cより前にAとB、Dより前にCを置く必要があり、この順序は全ての依存関係を満たします。',
    wrong: [['A, C, B, D', 'Cを処理する前に依存元Bも完了している必要があります。'], ['C, A, B, D', 'Cの前提であるAとBが後になっています。'], ['D, C, A, B', '依存される側を先に実行する順序です。']],
    position: 0, difficulty: 3,
  },
  {
    id: 'b-algorithm-065', topic: 'ダイクストラ法の更新',
    stem: '始点Sからの暫定距離を更新するダイクストラ法で、頂点Bの新しい距離を求める。',
    code: '手続 relax\ndist[A] ← 4\ndist[B] ← 9\nAからBへの辺の重み ← 3\n候補 ← dist[A] + 3\nif 候補 < dist[B] then dist[B] ← 候補 endif\nreturn dist[B]',
    answer: '7', why: 'SからAまで4、AからBまで3なので候補は7となり、既存の9を更新します。',
    wrong: [['3', 'AからBの辺の重みだけで始点からの距離としていません。'], ['4', 'Aまでの距離に辺の重みを加えていません。'], ['9', '候補7による更新を行わない値です。']],
    position: 2, difficulty: 3,
  },
  {
    id: 'b-algorithm-066', topic: '動的計画法',
    stem: '階段を1段または2段ずつ上る方法数を、前二つの結果から計算する。f(1)=1、f(2)=2のときf(4)はどれか。',
    code: '手続 stairs(n)\nf[1] ← 1\nf[2] ← 2\nfor i ← 3 to n\n  f[i] ← f[i-1] + f[i-2]\nendfor\nreturn f[n]',
    answer: '5', why: 'f(3)=2＋1=3、f(4)=3＋2=5と、直前二つの結果を足して求めます。',
    wrong: [['4', '段数nをそのまま方法数として扱っています。'], ['6', 'f(3)とf(2)ではなく、異なる添字の値を加えています。'], ['8', '前二つを足す更新を一回多く適用しています。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-algorithm-067', topic: '最短経路の動的計画法',
    stem: '右または下だけへ移動できる表で、左上から各マスまでの最小コストを更新する。右下の値はどれか。',
    code: '手続 grid\ncost ← [[1,2,4],[2,1,3],[5,2,1]]\ndp[1][1] ← 1\ndp[i][j] ← cost[i][j] + min(dp[i-1][j], dp[i][j-1])\nreturn dp[3][3]',
    answer: '7', why: '最小経路は1→2→1→2→1の順に進む経路で、合計7になります。',
    wrong: [['5', '移動できない斜め方向を使ってコストを短くしています。'], ['6', '左上から右下までの別経路のコストを取り違えています。'], ['16', '表全体のコストを合計しています。']],
    position: 3, difficulty: 3,
  },
  {
    id: 'b-algorithm-068', topic: '貪欲法',
    stem: '硬貨1、5、10を使って金額18を支払う貪欲法で、選ばれる硬貨の枚数を求める。',
    code: '手続 coins\namount ← 18\ncoins ← [10, 5, 1]\nc ← 0\nfor each coin in coins\n  while amount >= coin\n    amount ← amount - coin\n    c ← c + 1\n  endwhile\nendfor\nreturn c',
    answer: '5枚', why: '10を1枚、5を1枚、1を3枚選ぶので、合計5枚になります。',
    wrong: [['4枚', '18を10＋5＋1＋1と数え、1枚分を落としています。'], ['6枚', '5を2枚使った後の残額を過大に数えています。'], ['18枚', '金額を硬貨枚数と直接同じにしています。']],
    position: 0, difficulty: 2,
  },
  {
    id: 'b-algorithm-069', topic: '分割統治',
    stem: '入力を半分に分けて各部分を再帰的に処理し、最後に線形時間で統合する処理の計算量はどれか。',
    code: '手続 divide(a)\nif length(a) <= 1 then return a\nleft, right ← aを半分に分割\nreturn merge(divide(left), divide(right))',
    answer: 'O(n log n)', why: '分割の深さがlog nで、各段階の統合に合計O(n)かかるためO(n log n)です。',
    wrong: [['O(n)', '分割の各段階が一段だけだと考えています。'], ['O(n²)', '各段階で全要素対を比較する処理ではありません。'], ['O(log n)', '統合に必要な要素数nを含めていません。']],
    position: 2, difficulty: 3,
  },
  {
    id: 'b-algorithm-070', topic: '最小公倍数',
    stem: '最大公約数を使って12と18の最小公倍数を計算する式を実行した結果はどれか。',
    code: '手続 lcm\na ← 12, b ← 18\ng ← gcd(a, b)\nreturn a div g * b',
    answer: '36', why: '最大公約数gは6なので、12 div 6×18を計算すると36になります。',
    wrong: [['6', 'これは最大公約数であり、最小公倍数ではありません。'], ['30', '二つの入力値を加えた値で計算しています。'], ['216', '最大公約数で割らずに積だけを求めています。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-algorithm-071', topic: 'ビット演算',
    stem: '整数5と3のビット単位XORを計算した結果はどれか。',
    code: '手続 xor\na ← 5  // 101\nb ← 3  // 011\nreturn a XOR b',
    answer: '6', why: '101 XOR 011は各ビットが異なる位置だけ1となる110で、10進数の6です。',
    wrong: [['1', '論理積ANDの結果001と取り違えています。'], ['7', '論理和ORの結果111と取り違えています。'], ['8', '桁を加算して繰上げた値ではありません。']],
    position: 3, difficulty: 2,
  },
  {
    id: 'b-algorithm-072', topic: 'ビットマスク',
    stem: '下位ビットを1にするマスクをOR演算したとき、フラグ値の結果を求める。',
    code: '手続 setFlags\nflags ← 1000(2)\nmask ← 0011(2)\nflags ← flags OR mask\nreturn flags',
    answer: '1011(2)', why: 'ORではどちらかが1のビットが1になるため、下位二ビットが設定され1011になります。',
    wrong: [['1000(2)', 'マスクとのOR演算によるビット設定を反映していません。'], ['0011(2)', '元のflagsを捨て、maskだけを返しています。'], ['0000(2)', 'ORではなく反転やANDの結果と混同しています。']],
    position: 0, difficulty: 2,
  },
  {
    id: 'b-algorithm-073', topic: '1ビット数',
    stem: '整数13の二進表現に含まれる1の個数を、右端の1を消す更新で数える。',
    code: '手続 countBits\nx ← 13  // 1101(2)\nc ← 0\nwhile x != 0\n  x ← x AND (x - 1)\n  c ← c + 1\nendwhile\nreturn c',
    answer: '3', why: '1101には1が三つあり、x AND(x−1)は右端の1を一つずつ消すため3回です。',
    wrong: [['2', '13を二進数の桁数と取り違えています。'], ['4', '全てのビット位置を回数として数えています。'], ['13', 'ビット値そのものを返す処理ではありません。']],
    position: 2, difficulty: 3,
  },
  {
    id: 'b-algorithm-074', topic: '文字列探索',
    stem: '文字列内でパターンが初めて一致する添字を、先頭から一文字ずつ調べる処理で求める。',
    code: '手続 find\ntext ← "ABCADE"\npattern ← "CAD"\nfor i ← 1 to length(text)-length(pattern)+1\n  if text[i..i+2] = pattern then return i endif\nendfor\nreturn -1',
    answer: '3', why: 'textの3文字目からの部分列がCADと一致するため、初めての位置3を返します。',
    wrong: [['2', '2文字目からはBCAとなりパターンに一致しません。'], ['4', '4文字目からはADEとなり一致しません。'], ['-1', '一致する位置がない場合の返却値です。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-algorithm-075', topic: 'ランレングス符号化',
    stem: '同じ文字の連続回数を数字で表すランレングス符号化を行った結果はどれか。',
    code: '手続 encode\ns ← "AAABBCC"\n連続文字ごとに文字と回数をresultへ追加する\nreturn result',
    answer: 'A3B2C2', why: 'Aが3回、Bが2回、Cが2回連続するため、各文字と回数を順に連結します。',
    wrong: [['A3B3C1', 'BとCの連続回数を取り違えています。'], ['3A2B2C', '文字と回数の出力順を逆にしています。'], ['ABC7', '各文字の回数を個別に記録していません。']],
    position: 3, difficulty: 1,
  },
  {
    id: 'b-algorithm-076', topic: '行列転置',
    stem: '2行3列の行列を転置したときの行列の形と要素配置を求める。',
    code: '手続 transpose\na ← [[1,2,3],[4,5,6]]\nfor i ← 1 to 2\n  for j ← 1 to 3\n    b[j][i] ← a[i][j]\n  endfor\nendfor\nreturn b',
    answer: '[[1,4],[2,5],[3,6]]', why: '元のa[i][j]をb[j][i]へ置くため、行と列が入れ替わった3行2列になります。',
    wrong: [['[[1,2,3],[4,5,6]]', '元行列をそのまま返しており添字の交換をしていません。'], ['[[3,2,1],[6,5,4]]', '転置ではなく各行の左右反転になっています。'], ['[[1,2],[3,4],[5,6]]', '要素の並べ替えが元の行列の対応と異なります。']],
    position: 0, difficulty: 2,
  },
  {
    id: 'b-algorithm-077', topic: '二次元配列の走査',
    stem: '3行3列の配列で主対角線以外の要素を合計する処理の結果を求める。',
    code: '手続 offDiagonal\nm ← [[1,2,3],[4,5,6],[7,8,9]]\ns ← 0\nfor i ← 1 to 3\n  for j ← 1 to 3\n    if i != j then s ← s + m[i][j] endif\n  endfor\nendfor\nreturn s',
    answer: '30', why: '全体45から主対角線1、5、9の合計15を除くので、結果は30になります。',
    wrong: [['15', '主対角線上の要素だけを合計した値です。'], ['34', '対角線上の要素を一つだけ除外した値です。'], ['45', '除外条件を適用せず全要素を合計しています。']],
    position: 2, difficulty: 2,
  },
  {
    id: 'b-algorithm-078', topic: 'ハッシュ探索の再試行',
    stem: 'ハッシュ表の衝突を線形探索で解決するとき、末尾から先頭へ戻って最初に空く添字を求める。',
    code: '手続 wrapProbe\ntable[6], table[7]は使用中\nindex ← 6\nwhile table[index] is 使用中\n  index ← (index + 1) mod 8\nendwhile\nreturn index',
    answer: '0', why: '6、7が使用中なら次は(7＋1) mod 8で0へ戻り、そこが最初の空きになります。',
    wrong: [['6', '開始位置は使用中と条件に示されています。'], ['7', '次の添字も使用中なので停止できません。'], ['8', '表の添字は0から7で、8は剰余後に0になります。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-algorithm-079', topic: 'ループ不変条件',
    stem: '最大値を求めるループで、各反復の開始時に成立する不変条件として適切なものはどれか。',
    code: '手続 maximum\na ← [6, 2, 9, 4]\nm ← a[1]\nfor i ← 2 to 4\n  if a[i] > m then m ← a[i] endif\nendfor\nreturn m',
    answer: 'mは調査済み範囲の最大値である', why: '各反復後にmを調査済み要素の最大値へ更新するため、次の反復でもこの条件が保たれます。',
    wrong: [['mはその時点で配列全体の最大値である', '未調査要素をまだ比較していないため、その時点では保証できません。'], ['mは最後に見た要素である', '現在値がmより大きい場合だけ更新します。'], ['mは調査済み要素の合計である', '更新式は加算ではなく最大値との比較です。']],
    position: 3, difficulty: 3,
  },
  {
    id: 'b-algorithm-080', topic: '計算量の最悪値',
    stem: '整列済み配列へない値を二分探索したとき、要素数64で比較回数の上限はいくつか。',
    code: '手続 absent\nn ← 64\nc ← 0\nwhile n > 0\n  n ← n div 2\n  c ← c + 1\nendwhile\nreturn c',
    answer: '7回', why: '64、32、16、8、4、2、1、0と7回の判定で探索範囲が空になります。',
    wrong: [['6回', '最後の1要素を調べて空にする判定を数えていません。'], ['32回', '線形探索の比較回数と取り違えています。'], ['64回', '二分探索で毎回半分になることを反映していません。']],
    position: 0, difficulty: 3,
  },
];

const securitySeeds: QuestionSeed[] = [
  {
    id: 'b-security-011', topic: '最小権限',
    stem: '開発担当者が本番データベースを参照する必要がある。業務を止めずにリスクを抑える権限設計はどれか。',
    answer: '必要な表だけを読取り専用で許可し、期限付きで付与する',
    why: '目的に必要な最小範囲と期間だけに限定すれば、誤操作や漏えい時の影響を小さくできます。',
    wrong: [['開発担当者へ本番DBの管理者権限を恒久的に付与する', '作業範囲を超える更新や設定変更まで可能になります。'], ['全社員へ同じ参照権限を付与する', '利用者を限定できず、最小権限の原則に反します。'], ['権限を付与せず画面を共有して作業する', '記録と本人確認が不十分で、別の情報漏えいを招きます。']],
    position: 2, difficulty: 2,
  },
  {
    id: 'b-security-012', topic: 'インシデント初動',
    stem: '社内端末から外部へ大量通信が続いている。原因が不明な段階で担当者が最初に行う対応はどれか。',
    answer: '端末をネットワークから隔離し、ログと状況を保全して報告する',
    why: '通信の拡大を止めながら証拠を残し、組織のインシデント対応手順へ引き継ぐことが優先です。',
    wrong: [['端末をすぐ初期化して通常業務へ戻す', '原因と侵害範囲を調査する証拠を失います。'], ['担当者の判断で外部通信先へ返信する', '攻撃者へ追加情報を与え、状況を悪化させる可能性があります。'], ['全社の端末を同時に停止する', '影響範囲が不明な段階で過大な業務停止を招きます。']],
    position: 0, difficulty: 2,
  },
  {
    id: 'b-security-013', topic: 'クロスサイトスクリプティング対策',
    stem: '掲示板が利用者の入力をHTMLへ表示する。保存型XSSを防ぐ実装として最も適切なものはどれか。',
    answer: '表示時にHTMLとして解釈されないよう出力エスケープを行う',
    why: '利用者入力をタグやスクリプトとして実行させず、表示する文字列として扱うことが基本対策です。',
    wrong: [['入力欄の文字数を増やして長い入力を受け入れる', '入力可能な長さはスクリプト実行の解釈を防ぎません。'], ['エラー画面だけへ同じ入力を表示する', '表示箇所が残ればスクリプト実行の機会も残ります。'], ['DBのバックアップ世代を増やす', '復旧には役立ちますが、ブラウザ上の実行を防ぎません。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-security-014', topic: 'CSRF対策',
    stem: 'ログイン済み利用者のブラウザから意図しない送金操作が実行される問題を防ぐ対策はどれか。',
    answer: '状態変更要求へセッションと結び付いたCSRFトークンを付けて検証する',
    why: '正規画面から発行された要求かを確認でき、攻撃サイトから勝手に送られた要求を拒否できます。',
    wrong: [['送金画面の背景色を毎回変える', '表示の変更は要求の出所を検証しません。'], ['利用者のIDをURLへ含めるだけにする', '識別子を表示しても正規要求かどうかは確認できません。'], ['操作ログを保存せず処理を高速化する', '記録を減らしても不正要求の実行は防げません。']],
    position: 3, difficulty: 3,
  },
  {
    id: 'b-security-015', topic: '脆弱性管理',
    stem: 'ある組織の複数のサーバに異なる重要度の脆弱性が見つかった。修正計画の優先順位を決める基準として適切なものはどれか。',
    answer: '悪用可能性、資産の重要度、公開範囲を組み合わせて決める',
    why: '深刻度だけでなく、攻撃されやすさと業務影響を合わせることで、限られた作業時間を適切に配分できます。',
    wrong: [['発見順だけで修正する', '発見順は攻撃リスクや業務影響を表しません。'], ['担当者が修正しやすいサーバから着手する', '容易さだけでは重要な公開資産を後回しにする可能性があります。'], ['全サーバを同時に停止して修正する', '対象と影響を考えない一律停止で業務継続性を損ないます。']],
    position: 0, difficulty: 2,
  },
  {
    id: 'b-security-016', topic: '多層防御',
    stem: 'ある組織で一つの対策が突破されても被害を抑えるため、複数の異なる対策を組み合わせる考え方はどれか。',
    answer: '多層防御',
    why: '認証、アクセス制御、監視、バックアップなど複数の防御層を重ね、単一障害点を減らします。',
    wrong: [['単一障害点の集中', '一つの仕組みに依存しており、対策を重ねる考え方と逆です。'], ['性能試験の分割', '処理性能の検証方法であり、セキュリティ対策の層とは異なります。'], ['データ正規化', 'データベース設計の重複整理を表す用語です。']],
    position: 2, difficulty: 1,
  },
  {
    id: 'b-security-017', topic: '暗号化の使い分け',
    stem: 'あるサービスが保存中の顧客情報を、ディスクを持ち出されても読めないようにする対策はどれか。',
    answer: '保存データを暗号化し、鍵をデータと分離して管理する',
    why: '記憶媒体上のデータを暗号化し、鍵の管理経路も分けることで媒体単体からの読み出しを防ぎます。',
    wrong: [['通信路だけを暗号化し保存時は平文にする', '通信中は守れても、持ち出されたディスク上の情報は読めます。'], ['パスワードを画面に表示しない', '画面表示制御だけでは保存データの読み出しを防ぎません。'], ['ログの保存期間を延長する', '監査情報は増えますが、顧客データの内容は保護できません。']],
    position: 1, difficulty: 2,
  },
  {
    id: 'b-security-018', topic: 'バックアップ復旧',
    stem: 'ある組織でランサムウェアにより本番データが暗号化された場合にも復旧できるバックアップ運用はどれか。',
    answer: '本番と分離した世代管理バックアップを保管し、復元を定期検証する',
    why: '攻撃で本番と同時に失うことを避け、実際に復元できるかを確認して復旧手順の不備も見つけます。',
    wrong: [['本番共有フォルダへバックアップを上書きする', '本番と同じ攻撃でバックアップも暗号化されるおそれがあります。'], ['取得成功のログだけを確認し復元試験は行わない', '保存できても復元不能なデータや手順不備を見逃します。'], ['最新世代だけを残して古い世代を削除する', '暗号化済みデータが上書きされると正常な世代を失います。']],
    position: 3, difficulty: 2,
  },
  {
    id: 'b-security-019', topic: 'ネットワーク分離',
    stem: 'ある組織で業務端末がマルウェアに感染したとき、サーバへの横展開を抑える設計として適切なものはどれか。',
    answer: '業務上必要な通信だけを許可するネットワーク分離とアクセス制御を行う',
    why: '端末と重要サーバの到達範囲を限定すれば、一台の感染が全体へ広がる経路を減らせます。',
    wrong: [['全ネットワークを同一セグメントで接続する', '感染端末から多くの資産へ到達できる範囲を広げます。'], ['端末名を分かりやすく変更する', '名前の変更は通信経路やアクセス権を制御しません。'], ['通信ログを保存せず監視負荷を下げる', '侵害の把握と追跡に必要な情報を失います。']],
    position: 0, difficulty: 3,
  },
  {
    id: 'b-security-020', topic: '委託先インシデント対応',
    stem: 'ある組織で、顧客情報を扱う委託先から情報漏えいの疑いが報告された。委託元の初動として適切なものはどれか。',
    answer: '契約の連絡窓口で事実、影響範囲、封じ込め状況を確認し共同対応する',
    why: '委託先任せにせず、契約で定めた報告と証拠保全を使って影響を把握し、必要な通知と復旧へ進みます。',
    wrong: [['委託先との契約をその場で破棄し調査を終える', '関係を切るだけでは漏えい範囲や原因を確認できません。'], ['顧客への説明を避けるためログを削除する', '証拠を失い、事実確認と説明責任を果たせなくなります。'], ['委託先の担当者個人へ直接送金を求める', '正式なインシデント対応や契約上の責任分界から外れています。']],
    position: 2, difficulty: 3,
  },
];

export const additionalAlgorithmQuestions = makeQuestions('B', 'algorithm', '05-algorithms', algorithmSeeds);
export const additionalSecurityCaseQuestions = makeQuestions('B', 'security-case', '08-security', securitySeeds);
