import { makeQuestions, type QuestionSeed } from './helpers';

type AlgorithmCard = {
  topic: string; scenario: string; code: string; answer: string;
  why: string; wrong: [string, string][]; difficulty?: 1 | 2 | 3;
};

const cards: AlgorithmCard[] = [
  { topic:'ループ', scenario:'整数1から5までを順に合計する処理について、表示される値を求める。', code:'手続 total\nsum ← 0\nfor i ← 1 to 5\n  sum ← sum + i\nendfor\nreturn sum', answer:'15', why:'1＋2＋3＋4＋5の順に加算され、最終値は15になります。', wrong:[['10','最後の5を加える前の途中結果です。'],['20','ループ回数を加算値と混同した結果です。'],['25','5を5回加える処理ではありません。']] },
  { topic:'条件分岐', scenario:'三つの異なる整数の最大値を更新していく処理について、返却値を追跡する。', code:'手続 max3\nx ← 7, y ← 12, z ← 9\nm ← x\nif y > m then m ← y endif\nif z > m then m ← z endif\nreturn m', answer:'12', why:'7から開始し、yの12で更新後、zの9では更新されないため12です。', wrong:[['7','初期値のままで更新を反映していません。'],['9','最後に調べた値が返るわけではありません。'],['28','三つの数を合計する処理ではありません。']] },
  { topic:'剰余', scenario:'購入番号を3で分類する簡単なハッシュ処理で、指定番号の格納先を求める。', code:'手続 bucket\nkey ← 47\nindex ← key mod 3\nreturn index', answer:'2番', why:'47を3で割った余りは2なので、返される格納先は2番です。', wrong:[['0番','47は3の倍数ではないため余り0ではありません。'],['1番','46を3で割った場合の余りに相当します。'],['3番','剰余の結果は除数3より小さくなります。']] },
  { topic:'カウント', scenario:'センサー値の配列から基準値以上の要素数を数える処理を最後まで実行する。', code:'手続 countHigh\na ← [4, 8, 3, 9, 8]\nc ← 0\nfor each v in a\n  if v >= 8 then c ← c + 1 endif\nendfor\nreturn c', answer:'3個', why:'条件を満たす値は8、9、8の三つなので、カウンタは3になります。', wrong:[['2個','同じ値8の二回目を数え落としています。'],['4個','4は基準値8以上ではありません。'],['5個','全要素ではなく条件を満たす要素だけを数えます。']] },
  { topic:'while', scenario:'在庫量を半分ずつ切り捨てながら、正の間に何回更新できるかを数える。', code:'手続 halve\nn ← 20\nc ← 0\nwhile n > 0\n  n ← n div 2\n  c ← c + 1\nendwhile\nreturn c', answer:'5回', why:'20→10→5→2→1→0の五回更新で条件が偽になるため5回です。', wrong:[['4回','1から0への最後の更新も実行されます。'],['6回','0になった後はループを実行しません。'],['10回','2ずつ減らす処理ではありません。']] },
  { topic:'文字列', scenario:'入力文字列を末尾から先頭へ読み、別の文字列へ連結する処理結果を確認する。', code:'手続 reverse\ns ← "FE24"\nr ← ""\nfor i ← length(s) downto 1\n  r ← r + s[i]\nendfor\nreturn r', answer:'42EF', why:'末尾の4、2、E、Fの順に連結するので、結果は42EFです。', wrong:[['FE24','走査方向が末尾から先頭である点を反映していません。'],['24FE','二文字単位で交換する処理ではありません。'],['4E2F','添字を一つずつ逆順に読む結果と異なります。']] },
  { topic:'累乗', scenario:'底を繰り返し乗算して正の整数指数の累乗を計算する手続を追跡する。', code:'手続 power\nbase ← 3, exp ← 4\nr ← 1\nfor i ← 1 to exp\n  r ← r * base\nendfor\nreturn r', answer:'81', why:'1に3を四回乗じるため、3の4乗である81が返されます。', wrong:[['12','底と指数を乗算した値ではありません。'],['64','4の3乗を計算した値に相当します。'],['243','3を五回乗じた値で一回多いです。']] },
  { topic:'最大公約数', scenario:'ユークリッドの互除法で84と30の最大公約数を求める処理を評価する。', code:'手続 gcd\na ← 84, b ← 30\nwhile b != 0\n  t ← a mod b\n  a ← b\n  b ← t\nendwhile\nreturn a', answer:'6', why:'余りは24、6、0と変化し、最後にaへ残る6が最大公約数です。', wrong:[['2','両方を割れる値ですが最大ではありません。'],['12','30は12で割り切れないため公約数ではありません。'],['114','二つの入力値を加算する処理ではありません。']] },
  { topic:'フラグ', scenario:'会員番号の配列を先頭から調べ、目的の番号が見つかったかを真偽値で返す。', code:'手続 contains\na ← [13, 21, 34, 55]\nfound ← false\nfor each v in a\n  if v = 34 then found ← true endif\nendfor\nreturn found', answer:'true', why:'三番目の要素34が条件に一致するため、foundはtrueへ更新されます。', wrong:[['false','配列内に目的値34が存在しています。'],['34','返すのは要素値ではなく真偽フラグです。'],['3','一致位置の添字を返す処理ではありません。']] },
  { topic:'偶奇', scenario:'1から10までのうち偶数だけを選んで合計する処理について結果を計算する。', code:'手続 evenSum\ns ← 0\nfor i ← 1 to 10\n  if i mod 2 = 0 then s ← s + i endif\nendfor\nreturn s', answer:'30', why:'偶数2、4、6、8、10を合計すると30になるため、この値が返ります。', wrong:[['25','奇数1、3、5、7、9の合計です。'],['20','偶数の個数と最大値を掛けていません。'],['55','1から10まで全てを合計した値です。']] },
  { topic:'配列更新', scenario:'売上配列の各要素へ一律2を加えるループ後、中央の要素を参照する。', code:'手続 adjust\na ← [5, 7, 9]\nfor i ← 1 to 3\n  a[i] ← a[i] + 2\nendfor\nreturn a[2]', answer:'9', why:'配列は[7, 9, 11]へ更新され、二番目の要素は9になります。', wrong:[['7','更新前の二番目の値を選んでいます。'],['11','更新後の三番目の要素に相当します。'],['23','全要素の合計を返す手続ではありません。']] },
  { topic:'二重ループ', scenario:'3行4列のマスを二重ループで一度ずつ処理し、処理回数を数える。', code:'手続 cells\nc ← 0\nfor row ← 1 to 3\n  for col ← 1 to 4\n    c ← c + 1\n  endfor\nendfor\nreturn c', answer:'12回', why:'外側3回ごとに内側を4回実行するので、3×4で12回です。', wrong:[['7回','二つの反復回数を足す計算ではありません。'],['8回','外側の三回目を反映できていません。'],['16回','4×4の正方形を処理するわけではありません。']] },
  { topic:'添字', scenario:'五つの点数を逆順に別配列へ写したとき、新配列の二番目を取り出す。', code:'手続 reversedSecond\na ← [11, 22, 33, 44, 55]\nfor i ← 1 to 5\n  b[i] ← a[6 - i]\nendfor\nreturn b[2]', answer:'44', why:'bは[55,44,33,22,11]となるため、二番目は44です。', wrong:[['22','元配列の二番目であり、逆順変換後とは異なります。'],['33','中央要素は変わりませんが二番目ではありません。'],['55','逆順配列の先頭要素に相当します。']] },
  { topic:'平均との差', scenario:'四日分の処理件数から平均を求め、最大値との差を返す集計手続を実行する。', code:'手続 gap\na ← [6, 10, 14, 18]\ns ← 0\nfor each v in a\n  s ← s + v\nendfor\navg ← s div 4\nreturn 18 - avg', answer:'6', why:'合計48を4で割った平均は12で、最大値18との差は6です。', wrong:[['12','これは配列の平均値そのものです。'],['18','最大値から平均を引く処理が残っています。'],['30','平均ではなく最小値を引いた場合とも異なります。']] },
  { topic:'隣接差', scenario:'昇順の時刻配列で隣り合う値の差を計算し、その最大値を更新する。', code:'手続 maxGap\na ← [2, 5, 11, 14]\nm ← 0\nfor i ← 2 to 4\n  d ← a[i] - a[i-1]\n  if d > m then m ← d endif\nendfor\nreturn m', answer:'6', why:'隣接差は3、6、3であり、その最大値として6が残ります。', wrong:[['3','最初と最後の差だけを見た値です。'],['9','二つの隣接差を加える処理ではありません。'],['12','最大値と最小値の差に相当します。']] },
  { topic:'頻度表', scenario:'0から3の評価値を数えて頻度配列を作り、評価2の件数を取得する。', code:'手続 frequency\na ← [2, 1, 2, 3, 0, 2]\ncount ← [0, 0, 0, 0]\nfor each v in a\n  count[v] ← count[v] + 1\nendfor\nreturn count[2]', answer:'3件', why:'入力中の評価2は一、三、六番目に現れるため、頻度は3件です。', wrong:[['1件','値2の最初の出現だけを数えています。'],['2件','最後の出現を数え落としています。'],['6件','配列全体の要素数を返す処理ではありません。']] },
  { topic:'累積和', scenario:'日別アクセス数から累積和配列を作り、三日目までの合計値を参照する。', code:'手続 prefix\na ← [4, 7, 3, 8]\np[1] ← a[1]\nfor i ← 2 to 4\n  p[i] ← p[i-1] + a[i]\nendfor\nreturn p[3]', answer:'14', why:'累積値は4、11、14、22となり、三番目は14です。', wrong:[['10','一日目と二日目の一部を取り違えています。'],['18','三日目までではなく別の範囲の合計です。'],['22','これは四日分全ての累積値です。']] },
  { topic:'交換', scenario:'配列の先頭と末尾だけを一時変数で交換した後、先頭要素を確認する。', code:'手続 swapEnds\na ← [8, 6, 4, 2]\nt ← a[1]\na[1] ← a[4]\na[4] ← t\nreturn a[1]', answer:'2', why:'末尾の2が先頭へ代入されるので、交換後の先頭要素は2です。', wrong:[['8','交換前の先頭要素は末尾へ移動します。'],['4','中央の要素は交換処理の対象外です。'],['6','二番目の要素も交換処理の対象外です。']] },
  { topic:'行列', scenario:'2行2列の表で主対角線上の二要素だけを加算する処理を評価する。', code:'手続 diagonal\nm ← [[3, 5], [7, 11]]\ns ← 0\nfor i ← 1 to 2\n  s ← s + m[i][i]\nendfor\nreturn s', answer:'14', why:'主対角線の3と11だけを加えるため、結果は14になります。', wrong:[['8','一行目の二要素を加えた値です。'],['12','副対角線の5と7を加えた値です。'],['26','表の全要素を合計した値です。']] },
  { topic:'重複除去', scenario:'整列済み配列で直前と異なる値の個数を数え、異なる種類数を求める。', code:'手続 uniqueCount\na ← [1, 1, 3, 3, 3, 8]\nc ← 1\nfor i ← 2 to 6\n  if a[i] != a[i-1] then c ← c + 1 endif\nendfor\nreturn c', answer:'3種類', why:'値が変わる境界は1→3と3→8で、初期の1を含め3種類です。', wrong:[['2種類','値が変化した回数だけを答えています。'],['5種類','隣接する同じ値も別種類として数えています。'],['6種類','要素数と異なる値の種類数を混同しています。']] },
  { topic:'線形探索', scenario:'商品コード列を先頭から線形探索し、最初に一致する位置を返す処理を追跡する。', code:'手続 linearSearch\na ← [19, 23, 31, 42, 57]\ntarget ← 42\nfor i ← 1 to 5\n  if a[i] = target then return i endif\nendfor\nreturn 0', answer:'4番目', why:'42は配列の四番目で初めて一致するため、その添字4を返します。', wrong:[['3番目','三番目の値31は目的値と一致しません。'],['5番目','五番目の値は57であり目的値ではありません。'],['0番目','0は見つからなかった場合に返す値です。']] },
  { topic:'二分探索', scenario:'昇順に整列された七つの番号から25を二分探索するとき、最初に調べる値を求める。', code:'手続 firstProbe\na ← [4, 9, 15, 22, 25, 31, 40]\nlow ← 1, high ← 7\nmid ← (low + high) div 2\nreturn a[mid]', answer:'22', why:'中央添字は(1＋7) div 2で4となり、四番目の22を最初に調べます。', wrong:[['15','三番目であり中央添字の計算結果ではありません。'],['25','目的値でも、最初からその位置を調べるわけではありません。'],['31','六番目であり探索範囲の中央ではありません。']] },
  { topic:'バブルソート', scenario:'隣接要素を一回だけ左から比較交換する走査後の配列状態を確認する。', code:'手続 onePass\na ← [5, 2, 4, 1]\nfor i ← 1 to 3\n  if a[i] > a[i+1] then swap(a[i], a[i+1]) endif\nendfor\nreturn a', answer:'[2, 4, 1, 5]', why:'比較交換は5↔2、5↔4、5↔1の順で行われ、最大値5が末尾へ移ります。', wrong:[['[1, 2, 4, 5]','一回の走査だけでは全体の整列は完了しません。'],['[2, 5, 1, 4]','二回目以降の比較交換の結果が異なります。'],['[5, 2, 4, 1]','比較条件を満たすため配列は更新されます。']] },
  { topic:'選択ソート', scenario:'未整列部分から最小値を選び、先頭と一度だけ交換した配列を求める。', code:'手続 selectOnce\na ← [7, 3, 9, 2, 6]\nmin ← 1\nfor j ← 2 to 5\n  if a[j] < a[min] then min ← j endif\nendfor\nswap(a[1], a[min])\nreturn a', answer:'[2, 3, 9, 7, 6]', why:'最小値2の位置4を見つけ、先頭の7と交換するのでこの並びになります。', wrong:[['[3, 7, 9, 2, 6]','最初に小さい3だけで探索を終えていません。'],['[2, 3, 6, 7, 9]','一回の交換で全体は整列されません。'],['[7, 3, 9, 2, 6]','最小値を発見後に交換処理を実行します。']] },
  { topic:'挿入ソート', scenario:'整列済み部分[3,8,12]へ値6を挿入する一連の処理後の並びを選ぶ。', code:'手続 insert\na ← [3, 8, 12, 6]\nkey ← a[4]\nj ← 3\nwhile j >= 1 and a[j] > key\n  a[j+1] ← a[j]\n  j ← j - 1\nendwhile\na[j+1] ← key\nreturn a', answer:'[3, 6, 8, 12]', why:'12と8を右へずらし、3より大きい位置へ6を挿入するため昇順になります。', wrong:[['[6, 3, 8, 12]','6は3より大きいため先頭には入りません。'],['[3, 8, 6, 12]','8も右へ移動させる必要があります。'],['[3, 8, 12, 6]','比較と移動が行われるため元の並びではありません。']] },
  { topic:'マージ', scenario:'二つの昇順配列を先頭同士で比較して併合した結果を判断する。', code:'手続 merge\nx ← [2, 7, 10]\ny ← [1, 6, 9]\nwhile xとyに未処理要素がある\n  小さい先頭要素をresultへ追加する\nendwhile\n残りを追加する\nreturn result', answer:'[1, 2, 6, 7, 9, 10]', why:'各配列の先頭を比較して小さい順に取り出すため、全体が昇順に併合されます。', wrong:[['[2, 7, 10, 1, 6, 9]','単純連結ではなく先頭を比較して併合します。'],['[1, 6, 9, 2, 7, 10]','片方を全て先に取り出す処理ではありません。'],['[10, 9, 7, 6, 2, 1]','小さい値から追加するため降順にはなりません。']] },
  { topic:'探索量', scenario:'要素数64の整列済み配列を二分探索し、探索範囲を半分にする回数の上限を考える。', code:'手続 binarySteps\nn ← 64\nc ← 0\nwhile n > 1\n  n ← n div 2\n  c ← c + 1\nendwhile\nreturn c', answer:'6回', why:'64→32→16→8→4→2→1と六回半分にすると一要素になります。', wrong:[['5回','二要素から一要素への最後の半減も必要です。'],['8回','64は2の6乗なので八回ではありません。'],['32回','半分ずつ減らすため線形な回数にはなりません。']] },
  { topic:'ハッシュ', scenario:'配列長7の単純なハッシュ表でキー52を剰余法により配置する添字を求める。', code:'手続 hashIndex\nkey ← 52\nsize ← 7\nindex ← key mod size\nreturn index', answer:'3', why:'52を7で割ると商7、余り3なので、計算された添字は3です。', wrong:[['2','51を7で割った場合の余りに相当します。'],['5','キーの十の位を使う方式ではありません。'],['7','表サイズは除数であり剰余値ではありません。']] },
  { topic:'衝突', scenario:'線形探索法で衝突を解決するハッシュ表に、使用中の位置から次の空きを探す。', code:'手続 probe\ntable[2]とtable[3]は使用中\ni ← 2\nwhile table[i] is 使用中\n  i ← (i + 1) mod 8\nendwhile\nreturn i', answer:'4番', why:'2番、3番を順に調べると使用中であり、次の空き4番で停止します。', wrong:[['2番','開始位置は既に使用中なので格納できません。'],['3番','次の位置も使用中と条件に示されています。'],['5番','4番が空いているため、それより先へ進みません。']] },
  { topic:'番兵', scenario:'探索値を配列末尾へ番兵として追加して線形探索し、元配列内の一致を判定する。', code:'手続 sentinel\na ← [4, 8, 15, 16]\ntarget ← 23\na[5] ← target\ni ← 1\nwhile a[i] != target\n  i ← i + 1\nendwhile\nreturn i <= 4', answer:'false', why:'一致するのは追加した五番目の番兵だけなので、i<=4はfalseになります。', wrong:[['true','元の四要素には目的値23がありません。'],['5','返却式は添字ではなく真偽値を返します。'],['23','探索対象の値そのものを返す処理ではありません。']] },
  { topic:'スタック', scenario:'空のスタックへ三値を積み、一度取り出した後に最上部を参照するLIFO操作を追う。', code:'手続 stackTop\npush(5)\npush(9)\npush(12)\npop()\nreturn top()', answer:'9', why:'最後に積んだ12をpopで取り除くと、その下にある9が最上部になります。', wrong:[['5','5は最初に積んだ底の要素です。'],['12','12は直前のpop操作で取り除かれています。'],['26','スタック要素を合計する処理ではありません。']] },
  { topic:'キュー', scenario:'待ち行列へA、B、Cの順で追加し、一件取り出した後の先頭をFIFO規則で確認する。', code:'手続 queueFront\nenqueue("A")\nenqueue("B")\nenqueue("C")\ndequeue()\nreturn front()', answer:'B', why:'先入れ先出しなので最初のAが取り出され、次に古いBが先頭になります。', wrong:[['A','Aはdequeueによって既に取り出されています。'],['C','Cは最後に追加され、待ち行列の末尾です。'],['空','BとCが残っているため空にはなりません。']] },
  { topic:'連結リスト', scenario:'単方向リストの先頭へ新しい節点Xを挿入するとき、ポインタ操作後の順序を判断する。', code:'手続 prepend\nhead → A → B → null\nX.next ← head\nhead ← X\nreturn list', answer:'X → A → B', why:'Xの次を旧先頭Aにし、headをXへ変えるため、この順序になります。', wrong:[['A → X → B','Aのnextを書き換える処理は行っていません。'],['A → B → X','末尾を探索して追加する処理ではありません。'],['X → B → A','既存節点の順序は変更されません。']] },
  { topic:'木の走査', scenario:'二分木で左部分木、根、右部分木の順に節点を訪問する手続の名称を選ぶ。', code:'手続 traverse(node)\nif node != null then\n  traverse(node.left)\n  visit(node)\n  traverse(node.right)\nendif', answer:'中間順走査', why:'左部分木の後に根を訪れ、その後に右部分木を訪れるので中間順走査です。', wrong:[['先行順走査','先行順は根を左右の部分木より先に訪れます。'],['後行順走査','後行順は根を左右の部分木より後に訪れます。'],['幅優先走査','幅優先はキューを使い階層ごとに訪れます。']] },
  { topic:'二分探索木', scenario:'二分探索木へ値35を挿入する際、根30と右子40を比較した配置先を特定する。', code:'手続 insert35\nroot.value = 30, root.right.value = 40\nx ← 35\nif x > 30 then node ← root.right endif\nif x < node.value then node.left ← x endif\nreturn xの位置', answer:'40の左の子', why:'35は30より大きく40より小さいので、40の左側の子として配置されます。', wrong:[['30の左の子','35は根30より大きいため左へは進みません。'],['40の右の子','35は40より小さいため右側ではありません。'],['新しい根','既存の根を置き換える挿入処理ではありません。']] },
  { topic:'再帰', scenario:'正の整数nから1までを再帰的に乗算する関数へ5を渡した返却値を計算する。', code:'手続 f(n)\nif n = 1 then return 1\nelse return n * f(n - 1)\nendif', answer:'120', why:'5×4×3×2×1が計算されるため、返却値は階乗120になります。', wrong:[['15','5から1までを加算した値に相当します。'],['25','5を二乗する処理ではありません。'],['625','5を四回掛け続ける処理とは異なります。']] },
  { topic:'再帰トレース', scenario:'二つ前までの値を再帰的に足す関数について、基底条件を用いてg(5)を求める。', code:'手続 g(n)\nif n <= 1 then return n\nelse return g(n-1) + g(n-2)\nendif', answer:'5', why:'値はg(0)=0、g(1)=1から1、2、3、5と進むためg(5)=5です。', wrong:[['3','これは一つ前のg(4)の値です。'],['8','これは一つ先のg(6)の値です。'],['15','1から5までの合計を求める再帰ではありません。']] },
  { topic:'深さ優先探索', scenario:'グラフ探索で未訪問の隣接頂点を先へたどり、行き止まりで戻る実装の補助構造を選ぶ。', code:'手続 dfs(start)\nstack.push(start)\nwhile stack is not empty\n  v ← stack.pop()\n  if v is 未訪問 then visit(v) endif\nendwhile', answer:'スタック', why:'後から追加した頂点を先に取り出すLIFO構造により、深い方向へ探索します。', wrong:[['キュー','キューを使うと同じ深さを先に調べる幅優先探索になります。'],['ヒープ','優先度付き取出しはこの探索順の要件ではありません。'],['ハッシュ表','訪問済み管理には使えても探索順を単独では作れません。']] },
  { topic:'幅優先探索', scenario:'始点から辺の本数が少ない順に頂点を訪ねる探索を実装するため、次に調べる頂点を管理する。', code:'手続 bfs(start)\nqueue.enqueue(start)\nwhile queue is not empty\n  v ← queue.dequeue()\n  for each 未訪問の隣接頂点 u\n    queue.enqueue(u)\n  endfor\nendwhile', answer:'キュー', why:'先に発見した頂点を先に処理するFIFO構造で、距離の層ごとに探索できます。', wrong:[['スタック','スタックでは深い方向を優先する探索になります。'],['二分探索木','キー順検索の構造で探索の層順管理には使いません。'],['再帰呼出しだけ','典型的な再帰はLIFOとなり深さ優先に対応します。']] },
  { topic:'計算量', scenario:'長さnの配列を先頭から末尾まで一度だけ調べる処理の実行時間の増え方を評価する。', code:'手続 scan(a, n)\nfor i ← 1 to n\n  if a[i] < 0 then mark() endif\nendfor\nreturn done', answer:'O(n)', why:'各要素を一回ずつ調べるため、処理回数は要素数nに比例します。', wrong:[['O(1)','要素数が増えると反復回数も増えるため定数時間ではありません。'],['O(log n)','探索範囲を半分にする処理はありません。'],['O(n²)','入れ子の反復がないため二乗には増えません。']] },
  { topic:'二重反復の計算量', scenario:'全ての要素対を二重ループで比較する処理について、n増加時の比較回数の次数を判断する。', code:'手続 allPairs(a, n)\nfor i ← 1 to n\n  for j ← 1 to n\n    compare(a[i], a[j])\n  endfor\nendfor\nreturn done', answer:'O(n²)', why:'外側n回の各回で内側をn回行い、比較回数はn×nになります。', wrong:[['O(1)','反復回数は入力サイズに依存しています。'],['O(n)','一重ではなく二重の反復になっています。'],['O(2ⁿ)','部分集合を列挙する指数時間の処理ではありません。']] },
  { topic:'メモ化', scenario:'同じ引数の再帰計算を何度も行う関数を高速化するため、計算済み結果を再利用する方法を選ぶ。', code:'手続 solve(n)\nif memo[n] exists then return memo[n]\nif n <= 1 then return n\nmemo[n] ← solve(n-1) + solve(n-2)\nreturn memo[n]', answer:'メモ化', why:'引数ごとの結果を保存して再利用し、同じ部分問題の重複計算を避けています。', wrong:[['番兵法','探索配列の末尾へ探索値を置く方法ではありません。'],['排他制御','共有資源の同時更新を防ぐことが目的ではありません。'],['線形補間','二点間の値を推定する計算とは異なります。']] },
];

const seeds: QuestionSeed[] = cards.map((card, index) => ({
  id:`b-algorithm-${String(index + 1).padStart(3,'0')}`,
  topic:card.topic,
  stem:`${card.scenario} 次の擬似言語を実行または評価した結果として、最も適切なものはどれか。`,
  code:card.code,
  answer:card.answer,
  why:`${card.why} 変数と制御構造を上から順に追跡することが判断の要点です。`,
  wrong:card.wrong,
  position:(index % 4) as 0|1|2|3,
  difficulty:card.difficulty ?? (index < 10 ? 1 : index < 30 ? 2 : 3),
}));

export const algorithmQuestions = makeQuestions('B','algorithm','05-algorithms',seeds);
