import type { ExplanationVisual } from '../domain/types';

export const supplementalExplanationVisuals = Object.freeze({
  "b-exam-algorithm-001": {
    src: "/images/explanations/b-exam-algorithm-001.webp",
    alt: "二重ループ追跡について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "二重ループ追跡の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-002": {
    src: "/images/explanations/b-exam-algorithm-002.webp",
    alt: "二分探索の境界について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "二分探索の境界の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-003": {
    src: "/images/explanations/b-exam-algorithm-003.webp",
    alt: "連結リスト配列表現について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "連結リスト配列表現の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-004": {
    src: "/images/explanations/b-exam-algorithm-004.webp",
    alt: "循環キューについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "循環キューの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-005": {
    src: "/images/explanations/b-exam-algorithm-005.webp",
    alt: "スタック式評価について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "スタック式評価の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-006": {
    src: "/images/explanations/b-exam-algorithm-006.webp",
    alt: "再帰とメモ化について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "再帰とメモ化の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-007": {
    src: "/images/explanations/b-exam-algorithm-007.webp",
    alt: "安定ソートについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "安定ソートの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-008": {
    src: "/images/explanations/b-exam-algorithm-008.webp",
    alt: "幅優先探索について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "幅優先探索の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-009": {
    src: "/images/explanations/b-exam-algorithm-009.webp",
    alt: "深さ優先探索について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "深さ優先探索の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-010": {
    src: "/images/explanations/b-exam-algorithm-010.webp",
    alt: "ダイクストラ法について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ダイクストラ法の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-011": {
    src: "/images/explanations/b-exam-algorithm-011.webp",
    alt: "トポロジカルソートについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "トポロジカルソートの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-012": {
    src: "/images/explanations/b-exam-algorithm-012.webp",
    alt: "最小ヒープについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "最小ヒープの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-013": {
    src: "/images/explanations/b-exam-algorithm-013.webp",
    alt: "ハッシュ法について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ハッシュ法の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-014": {
    src: "/images/explanations/b-exam-algorithm-014.webp",
    alt: "累積和について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "累積和の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-015": {
    src: "/images/explanations/b-exam-algorithm-015.webp",
    alt: "スライディングウィンドウについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "スライディングウィンドウの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-016": {
    src: "/images/explanations/b-exam-algorithm-016.webp",
    alt: "二ポインタ法について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "二ポインタ法の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-017": {
    src: "/images/explanations/b-exam-algorithm-017.webp",
    alt: "二次元配列について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "二次元配列の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-018": {
    src: "/images/explanations/b-exam-algorithm-018.webp",
    alt: "文字列圧縮について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "文字列圧縮の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-019": {
    src: "/images/explanations/b-exam-algorithm-019.webp",
    alt: "ビットマスクについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ビットマスクの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-020": {
    src: "/images/explanations/b-exam-algorithm-020.webp",
    alt: "ビット列走査について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ビット列走査の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-021": {
    src: "/images/explanations/b-exam-algorithm-021.webp",
    alt: "動的計画法について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "動的計画法の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-022": {
    src: "/images/explanations/b-exam-algorithm-022.webp",
    alt: "ナップサック動的計画法について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ナップサック動的計画法の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-023": {
    src: "/images/explanations/b-exam-algorithm-023.webp",
    alt: "貪欲法について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "貪欲法の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-024": {
    src: "/images/explanations/b-exam-algorithm-024.webp",
    alt: "マージ処理について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "マージ処理の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-025": {
    src: "/images/explanations/b-exam-algorithm-025.webp",
    alt: "クイックソート分割について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "クイックソート分割の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-026": {
    src: "/images/explanations/b-exam-algorithm-026.webp",
    alt: "ループ不変条件について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ループ不変条件の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-027": {
    src: "/images/explanations/b-exam-algorithm-027.webp",
    alt: "境界条件修正について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "境界条件修正の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-028": {
    src: "/images/explanations/b-exam-algorithm-028.webp",
    alt: "番兵法について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "番兵法の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-029": {
    src: "/images/explanations/b-exam-algorithm-029.webp",
    alt: "状態遷移について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "状態遷移の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-030": {
    src: "/images/explanations/b-exam-algorithm-030.webp",
    alt: "木の走査について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "木の走査の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-031": {
    src: "/images/explanations/b-exam-algorithm-031.webp",
    alt: "二分探索木について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "二分探索木の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-algorithm-032": {
    src: "/images/explanations/b-exam-algorithm-032.webp",
    alt: "計算量について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "計算量の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-security-001": {
    src: "/images/explanations/b-exam-security-001.webp",
    alt: "認証ログ分析について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "認証ログ分析の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-security-002": {
    src: "/images/explanations/b-exam-security-002.webp",
    alt: "多要素認証について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "多要素認証の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-security-003": {
    src: "/images/explanations/b-exam-security-003.webp",
    alt: "バックアップ復旧について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "バックアップ復旧の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-security-004": {
    src: "/images/explanations/b-exam-security-004.webp",
    alt: "SQLインジェクション対策について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "SQLインジェクション対策の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-security-005": {
    src: "/images/explanations/b-exam-security-005.webp",
    alt: "クロスサイトスクリプティングについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "クロスサイトスクリプティングの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-security-006": {
    src: "/images/explanations/b-exam-security-006.webp",
    alt: "リクエスト偽造対策について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "リクエスト偽造対策の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-security-007": {
    src: "/images/explanations/b-exam-security-007.webp",
    alt: "最小権限について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "最小権限の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "b-exam-security-008": {
    src: "/images/explanations/b-exam-security-008.webp",
    alt: "委託先インシデントについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "委託先インシデントの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-01": {
    src: "/images/explanations/basic-set6-01.webp",
    alt: "ベイズの定理について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ベイズの定理の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-02": {
    src: "/images/explanations/basic-set6-02.webp",
    alt: "統計指標について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "統計指標の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-03": {
    src: "/images/explanations/basic-set6-03.webp",
    alt: "メモリ種別について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "メモリ種別の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-04": {
    src: "/images/explanations/basic-set6-04.webp",
    alt: "入出力インタフェースについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "入出力インタフェースの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-05": {
    src: "/images/explanations/basic-set6-05.webp",
    alt: "高信頼化設計について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "高信頼化設計の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-06": {
    src: "/images/explanations/basic-set6-06.webp",
    alt: "DDLとDMLについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "DDLとDMLの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-07": {
    src: "/images/explanations/basic-set6-07.webp",
    alt: "関数従属について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "関数従属の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-08": {
    src: "/images/explanations/basic-set6-08.webp",
    alt: "CSMA方式について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "CSMA方式の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-09": {
    src: "/images/explanations/basic-set6-09.webp",
    alt: "ネットワーク管理プロトコルについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ネットワーク管理プロトコルの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-10": {
    src: "/images/explanations/basic-set6-10.webp",
    alt: "脆弱性識別と評価について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "脆弱性識別と評価の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-11": {
    src: "/images/explanations/basic-set6-11.webp",
    alt: "監視と端末防御について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "監視と端末防御の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-12": {
    src: "/images/explanations/basic-set6-12.webp",
    alt: "DMZについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "DMZの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-13": {
    src: "/images/explanations/basic-set6-13.webp",
    alt: "開発プロセス標準について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "開発プロセス標準の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-14": {
    src: "/images/explanations/basic-set6-14.webp",
    alt: "設計パターンについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "設計パターンの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-15": {
    src: "/images/explanations/basic-set6-15.webp",
    alt: "アジャイル手法について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "アジャイル手法の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-16": {
    src: "/images/explanations/basic-set6-16.webp",
    alt: "サービスデスクについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "サービスデスクの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-17": {
    src: "/images/explanations/basic-set6-17.webp",
    alt: "市場成長戦略について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "市場成長戦略の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-18": {
    src: "/images/explanations/basic-set6-18.webp",
    alt: "生産管理について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "生産管理の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-19": {
    src: "/images/explanations/basic-set6-19.webp",
    alt: "取引関連法規について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "取引関連法規の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set6-20": {
    src: "/images/explanations/basic-set6-20.webp",
    alt: "標準化について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "標準化の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-01": {
    src: "/images/explanations/basic-set7-01.webp",
    alt: "遷移確率について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "遷移確率の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-02": {
    src: "/images/explanations/basic-set7-02.webp",
    alt: "PID制御について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "PID制御の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-03": {
    src: "/images/explanations/basic-set7-03.webp",
    alt: "クラウドサービスモデルについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "クラウドサービスモデルの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-04": {
    src: "/images/explanations/basic-set7-04.webp",
    alt: "多相性について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "多相性の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-05": {
    src: "/images/explanations/basic-set7-05.webp",
    alt: "スラッシングについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "スラッシングの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-06": {
    src: "/images/explanations/basic-set7-06.webp",
    alt: "E-Rモデルについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "E-Rモデルの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-07": {
    src: "/images/explanations/basic-set7-07.webp",
    alt: "無線LAN用語について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "無線LAN用語の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-08": {
    src: "/images/explanations/basic-set7-08.webp",
    alt: "HTTPSについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "HTTPSの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-09": {
    src: "/images/explanations/basic-set7-09.webp",
    alt: "CSIRTについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "CSIRTの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-10": {
    src: "/images/explanations/basic-set7-10.webp",
    alt: "暗号の危殆化について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "暗号の危殆化の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-11": {
    src: "/images/explanations/basic-set7-11.webp",
    alt: "ローコード開発について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ローコード開発の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-12": {
    src: "/images/explanations/basic-set7-12.webp",
    alt: "プロダクトオーナについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "プロダクトオーナの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-13": {
    src: "/images/explanations/basic-set7-13.webp",
    alt: "バーンダウンチャートについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "バーンダウンチャートの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-14": {
    src: "/images/explanations/basic-set7-14.webp",
    alt: "期間短縮手法について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "期間短縮手法の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-15": {
    src: "/images/explanations/basic-set7-15.webp",
    alt: "オムニチャネルについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "オムニチャネルの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-16": {
    src: "/images/explanations/basic-set7-16.webp",
    alt: "販売データ分析について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "販売データ分析の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-17": {
    src: "/images/explanations/basic-set7-17.webp",
    alt: "生成AI利用について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "生成AI利用の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-18": {
    src: "/images/explanations/basic-set7-18.webp",
    alt: "発想法について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "発想法の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-19": {
    src: "/images/explanations/basic-set7-19.webp",
    alt: "著作者人格権について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "著作者人格権の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set7-20": {
    src: "/images/explanations/basic-set7-20.webp",
    alt: "カーボンフットプリントについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "カーボンフットプリントの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-01": {
    src: "/images/explanations/basic-set8-01.webp",
    alt: "エッジコンピューティングについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "エッジコンピューティングの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-02": {
    src: "/images/explanations/basic-set8-02.webp",
    alt: "クリッピングについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "クリッピングの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-03": {
    src: "/images/explanations/basic-set8-03.webp",
    alt: "アンチエイリアシングについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "アンチエイリアシングの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-04": {
    src: "/images/explanations/basic-set8-04.webp",
    alt: "pingについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "pingの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-05": {
    src: "/images/explanations/basic-set8-05.webp",
    alt: "ドライブバイダウンロードについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ドライブバイダウンロードの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-06": {
    src: "/images/explanations/basic-set8-06.webp",
    alt: "ハイブリッドクラウドについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ハイブリッドクラウドの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-07": {
    src: "/images/explanations/basic-set8-07.webp",
    alt: "ダイバーシティマネジメントについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ダイバーシティマネジメントの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-08": {
    src: "/images/explanations/basic-set8-08.webp",
    alt: "イノベータ理論について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "イノベータ理論の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-09": {
    src: "/images/explanations/basic-set8-09.webp",
    alt: "CIOについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "CIOの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-10": {
    src: "/images/explanations/basic-set8-10.webp",
    alt: "ボリュームライセンスについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ボリュームライセンスの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-11": {
    src: "/images/explanations/basic-set8-11.webp",
    alt: "ロジックマッシュアップについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ロジックマッシュアップの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-12": {
    src: "/images/explanations/basic-set8-12.webp",
    alt: "アローダイアグラムについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "アローダイアグラムの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-13": {
    src: "/images/explanations/basic-set8-13.webp",
    alt: "ブルーオーシャンについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "ブルーオーシャンの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-14": {
    src: "/images/explanations/basic-set8-14.webp",
    alt: "HRテックについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "HRテックの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-15": {
    src: "/images/explanations/basic-set8-15.webp",
    alt: "SQL集合・範囲条件について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "SQL集合・範囲条件の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-16": {
    src: "/images/explanations/basic-set8-16.webp",
    alt: "回線利用率について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "回線利用率の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-17": {
    src: "/images/explanations/basic-set8-17.webp",
    alt: "2要素認証について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "2要素認証の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-18": {
    src: "/images/explanations/basic-set8-18.webp",
    alt: "二分探索木について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "二分探索木の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-19": {
    src: "/images/explanations/basic-set8-19.webp",
    alt: "クイックソートについて、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "クイックソートの解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
  "basic-set8-20": {
    src: "/images/explanations/basic-set8-20.webp",
    alt: "コーディング規約について、問題の条件から判断のポイント、正答までを順に図解した説明画像",
    label: "コーディング規約の解き方",
    description: "問題文の条件、判断のポイント、結論を順番に図で確認できます。",
  },
} satisfies Record<string, ExplanationVisual>);
