export const studyVisuals = [
  {
    id: 'roadmap',
    src: '/images/fe-roadmap.png',
    alt: '基本情報技術者試験の12章を基礎理論から最終復習までつなぐ学習ロードマップ',
    label: 'FE試験の学習ロードマップ',
    description: '12章を基礎から応用、最終確認までつなげて、今どこを学んでいるかを一枚で確認します。',
    relatedMaterialIds: ['01-roadmap'],
  },
  {
    id: 'theory',
    src: '/images/fe-theory.png',
    alt: '二進数と十六進数、論理ゲート、真理値表、文字コード、ビットとバイトを整理した情報理論図解',
    label: '情報理論と基礎表現',
    description: '基数変換、論理演算、文字コード、情報量を、表と回路のつながりで整理します。',
    relatedMaterialIds: ['02-theory'],
  },
  {
    id: 'computer',
    src: '/images/fe-computer.png',
    alt: 'CPUの制御装置、ALU、レジスタ、バス、メモリ階層、命令実行サイクルを示すコンピュータ構成図',
    label: 'コンピュータの構成要素',
    description: 'CPU内部の役割、バス、キャッシュ・RAM・ストレージの関係を一枚で確認します。',
    relatedMaterialIds: ['03-computer'],
  },
  {
    id: 'software',
    src: '/images/fe-software.png',
    alt: 'プロセス、スレッド、スケジューリング、仮想メモリ、ファイルシステム、APIを示すOS図解',
    label: 'OSとソフトウェア',
    description: 'OSがアプリケーションとハードウェアの間で何を管理するかを流れで理解します。',
    relatedMaterialIds: ['04-software'],
  },
  {
    id: 'algorithm',
    src: '/images/fe-algorithm.png',
    alt: 'フローチャート、探索、整列、配列、データ構造、計算量を示すアルゴリズム図解',
    label: 'アルゴリズムとデータ構造',
    description: '処理の流れ、データ構造、探索・整列、計算量を問題の追跡手順へつなげます。',
    relatedMaterialIds: ['05-algorithms'],
  },
  {
    id: 'database',
    src: '/images/fe-database.png',
    alt: '主キーと外部キー、第一から第三正規形、SQL、ACIDトランザクション、インデックスを示すデータベース図解',
    label: 'データベースの設計と処理',
    description: '正規化、SQL、トランザクション、インデックスを、設計から実行まで整理します。',
    relatedMaterialIds: ['06-database'],
  },
  {
    id: 'dns-ttl',
    src: '/images/fe-dns-ttl.png',
    alt: 'DNSリゾルバ、DNSサーバー、キャッシュ、TTL、有効期限後の再問い合わせを示す説明図',
    label: 'DNSとTTLのしくみ',
    description: '名前解決、キャッシュの有効期間、TTL切れ後の再問い合わせを流れで確認します。',
    relatedMaterialIds: ['07-network'],
  },
  {
    id: 'tcp-udp',
    src: '/images/fe-tcp-udp.png',
    alt: 'TCPとUDPの接続、再送、順序制御、低遅延の違いと通信層を比較する説明図',
    label: 'TCPとUDPの違い',
    description: '信頼性を優先するTCPと、低遅延を優先するUDPを条件で選び分けます。',
    relatedMaterialIds: ['07-network'],
  },
  {
    id: 'subnet-routing',
    src: '/images/fe-subnet-routing.png',
    alt: 'IPv4のネットワーク部とホスト部、サブネット分割、最長一致ルーティングを示す説明図',
    label: 'サブネットと最長一致',
    description: 'ネットワーク部・ホスト部、利用可能ホスト数、経路表の最長一致を一枚で整理します。',
    relatedMaterialIds: ['07-network', '02-theory'],
  },
  {
    id: 'auth-access-control',
    src: '/images/fe-auth-access-control.png',
    alt: '認証、認可、操作、監査ログ、多要素認証、最小権限の流れを示す説明図',
    label: '認証とアクセス制御',
    description: '認証は誰か、認可は何ができるか。MFAと最小権限まで流れで確認します。',
    relatedMaterialIds: ['08-security'],
  },
  {
    id: 'security-overview',
    src: '/images/fe-security.png',
    alt: '情報セキュリティの脅威、認証、アクセス制御、暗号、ネットワーク防御を示す全体図',
    label: '情報セキュリティの全体像',
    description: '脅威を見つけ、本人確認と権限制御を行い、暗号と防御で被害を抑える流れを確認します。',
    relatedMaterialIds: ['08-security'],
  },
  {
    id: 'development',
    src: '/images/fe-development.png',
    alt: '要件定義、設計、実装、テスト、リリース、運用保守とウォーターフォール・アジャイルを示す開発図解',
    label: 'システム開発と設計',
    description: '開発工程、ウォーターフォールとアジャイル、UML、バージョン管理を比較します。',
    relatedMaterialIds: ['09-development'],
  },
  {
    id: 'management',
    src: '/images/fe-management.png',
    alt: 'プロジェクト管理のスコープ、スケジュール、コスト、品質、リスクとサービス管理の流れを示す図解',
    label: 'プロジェクト・サービス管理',
    description: 'プロジェクトの計画と管理、サービスのインシデント・問題・変更管理をつなげます。',
    relatedMaterialIds: ['10-management'],
  },
  {
    id: 'strategy',
    src: '/images/fe-strategy.png',
    alt: '経営目標、KPI、バランススコアカード、SWOT、ERP、CRM、SCM、投資評価を示す戦略図解',
    label: '経営戦略と情報システム',
    description: '経営目標からKPI、業務システム、投資評価、コンプライアンスまでを一枚で確認します。',
    relatedMaterialIds: ['11-strategy'],
  },
  {
    id: 'final-review',
    src: '/images/fe-final-review.png',
    alt: 'FE試験の問題文の条件、観点、分野、よくある落とし穴、最終チェックを示す復習図解',
    label: 'FE試験の最終復習',
    description: '問題文の条件から観点を選び、分野別の落とし穴と最終チェックへ進む判断手順です。',
    relatedMaterialIds: ['12-final-review'],
  },
];
